name = "aafu"
license = "MIT"
licenselink = "https://github.com/darshanbaral/aafu/blob/master/LICENSE"
description = "Portfolio and blog theme with multiple theme colors"
homepage = "https://github.com/darshanbaral/aafu"
tags = ["portfolio", "accordion", "resume", "blog"]
features = ["responsive", "dark", "clean"]
min_version = "0.55"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
